@host = http://127.0.0.1:3333

GET {{host}}
###
GET {{host}}/users
###
POST {{host}}/users
content-type: application/json

{ "nome": "Elon", "sobrenome": "Musk", "email": "ellinho67@hotmail.com", "senha": "ilovejiminbts666" }
###
GET {{host}}/users/1
###
PATCH {{host}}/users/1
content-type: application/json

{ "sobrenome": "Reeve Musk" }
###
DELETE {{host}}/users/1

###
GET {{host}}/cart/1
###
POST {{host}}/cart/1
content-type: application/json

{ "hotelId": 1, "diarias": 2 }
###
PATCH {{host}}/cart/1/1
content-type: application/json

{ "diarias": 3 }
###
DELETE {{host}}/cart/1/1
###
DELETE {{host}}/cart/1
###
POST {{host}}/users/login
content-type: application/json

{ "email": "ellinho67@hotmail.com", "senha": "ilovejiminbts666" }
###
POST {{host}}/orders/1
content-type: application/json

{ "formaPagamento": "cartao", "parcelas": 3 }
###
GET {{host}}/orders/1
###
GET {{host}}/orders/1/1
